from typing import Protocol

class EncryptionService(Protocol):
    def encrypt(self, data: str | int) -> str: ...
    def decrypt(self, encrypted: str) -> str: ...

class HashingService(Protocol):
    def hash_password(self, password: str) -> str: ...
    def deterministic_hash(self, str_to_dhash: str) -> str: ...
    def compare_password(self, password: str, hashed_value: str) -> bool: ...

    